### ISSUE TITLE
Chroniker Job Fails: TimelineEventInserter

### ISSUE THREAD

**Issue by noisy** [noisy-witness/steemprojects.com#137]
```
The job failed to run. The exception was :

Steem Notify Service Exception:

10 assert_exception: Assert Exception
(now - auth.last_post) > STEEMIT_MIN_REPLY_INTERVAL: You may only comment once every 20 seconds.
{"now":"2018-03-10T00:10:30","auth.last_post":"2018-03-10T00:10:12"}
th_a steem_evaluator.cpp:511 do_apply

{"o":{"parent_author":"yabapmatt","parent_permlink":"another-price-feed-publishing-tool-for-witnesses","author":"steemprojects","permlink":"re-another-price-feed-publishing-tool-for-witnesses-20180310t001031","title":"","body":"\nThis post has been just added as new item to _[timeline of Witness Price Feed on Steem Projects](https://steemprojects.com/projects/p/witness-price-feed/)_.\n\nIf you want to be notified about new updates from this project, register on Steem Projects and add Witness Price Feed to your favorite projects.\n","json_metadata":""}}
th_a steem_evaluator.cpp:682 do_apply

{"op":["comment",{"parent_author":"yabapmatt","parent_permlink":"another-price-feed-publishing-tool-for-witnesses","author":"steemprojects","permlink":"re-another-price-feed-publishing-tool-for-witnesses-20180310t001031","title":"","body":"\nThis post has been just added as new item to _[timeline of Witness Price Feed on Steem Projects](https://steemprojects.com/projects/p/witness-price-feed/)_.\n\nIf you want to be notified about new updates from this project, register on Steem Projects and add Witness Price Feed to your favorite projects.\n","json_metadata":""}]}
th_a database.cpp:2893 _apply_transaction

{"trx":{"ref_block_num":25449,"ref_block_prefix":445264557,"expiration":"2018-03-10T00:11:31","operations":[["comment",{"parent_author":"yabapmatt","parent_permlink":"another-price-feed-publishing-tool-for-witnesses","author":"steemprojects","permlink":"re-another-price-feed-publishing-tool-for-witnesses-20180310t001031","title":"","body":"\nThis post has been just added as new item to _[timeline of Witness Price Feed on Steem Projects](https://steemprojects.com/projects/p/witness-price-feed/)_.\n\nIf you want to be notified about new updates from this project, register on Steem Projects and add Witness Price Feed to your favorite projects.\n","json_metadata":""}]],"extensions":[],"signatures":["1f278723ef27b9193073b5350ce2d7fa30d49da5593033271022972413c00b45b7684dd298098561ee7acf0f008dfb7b6476236c36c854df849cbe70d80b9cdf83"]}}
th_a database.cpp:2897 _apply_transaction

{"trx":{"ref_block_num":25449,"ref_block_prefix":445264557,"expiration":"2018-03-10T00:11:31","operations":[["comment",{"parent_author":"yabapmatt","parent_permlink":"another-price-feed-publishing-tool-for-witnesses","author":"steemprojects","permlink":"re-another-price-feed-publishing-tool-for-witnesses-20180310t001031","title":"","body":"\nThis post has been just added as new item to _[timeline of Witness Price Feed on Steem Projects](https://steemprojects.com/projects/p/witness-price-feed/)_.\n\nIf you want to be notified about new updates from this project, register on Steem Projects and add Witness Price Feed to your favorite projects.\n","json_metadata":""}]],"extensions":[],"signatures":["1f278723ef27b9193073b5350ce2d7fa30d49da5593033271022972413c00b45b7684dd298098561ee7acf0f008dfb7b6476236c36c854df849cbe70d80b9cdf83"]}}
th_a database.cpp:660 push_transaction

{"call.method":"call","call.params":["network_broadcast_api","broadcast_transaction",[{"ref_block_num":25449,"ref_block_prefix":445264557,"expiration":"2018-03-10T00:11:31","operations":[["comment",{"parent_author":"yabapmatt","parent_permlink":"another-price-feed-publishing-tool-for-witnesses","author":"steemprojects","permlink":"re-another-price-feed-publishing-tool-for-witnesses-20180310t001031","title":"","body":"\nThis post has been just added as new item to _[timeline of Witness Price Feed on Steem Projects](https://steemprojects.com/projects/p/witness-price-feed/)_.\n\nIf you want to be notified about new updates from this project, register on Steem Projects and add Witness Price Feed to your favorite projects.\n","json_metadata":""}]],"extensions":[],"signatures":["1f278723ef27b9193073b5350ce2d7fa30d49da5593033271022972413c00b45b7684dd298098561ee7acf0f008dfb7b6476236c36c854df849cbe70d80b9cdf83"]}]]}
th_a websocket_api.cpp:124 on_message

None


Traceback (most recent call last):

File "/app/timeline/services.py", line 109, in notify
resposnse = post.reply(msg, "", settings.STEEM_ACCOUNT)

File "/usr/local/lib/python3.6/site-packages/steem/post.py", line 312, in reply
reply_identifier=self.identifier)

File "/usr/local/lib/python3.6/site-packages/steem/commit.py", line 325, in post
return self.finalizeOp(ops, author, "posting")

File "/usr/local/lib/python3.6/site-packages/steem/commit.py", line 128, in finalizeOp
return tx.broadcast()

File "/usr/local/lib/python3.6/site-packages/steem/transactionbuilder.py", line 131, in broadcast
raise e

File "/usr/local/lib/python3.6/site-packages/steem/transactionbuilder.py", line 129, in broadcast
self.steemd.broadcast_transaction(self.json())

File "/usr/local/lib/python3.6/site-packages/steem/steemd.py", line 857, in broadcast_transaction
return self.exec('broadcast_transaction', signed_transaction, api='network_broadcast_api')

File "/usr/local/lib/python3.6/site-packages/steembase/http_client.py", line 186, in exec
return_with_args=return_with_args)

File "/usr/local/lib/python3.6/site-packages/steembase/http_client.py", line 206, in _return
raise RPCError(error_message)

steembase.exceptions.RPCError: 10 assert_exception: Assert Exception
(now - auth.last_post) > STEEMIT_MIN_REPLY_INTERVAL: You may only comment once every 20 seconds.
{"now":"2018-03-10T00:10:30","auth.last_post":"2018-03-10T00:10:12"}
th_a steem_evaluator.cpp:511 do_apply

{"o":{"parent_author":"yabapmatt","parent_permlink":"another-price-feed-publishing-tool-for-witnesses","author":"steemprojects","permlink":"re-another-price-feed-publishing-tool-for-witnesses-20180310t001031","title":"","body":"\nThis post has been just added as new item to _[timeline of Witness Price Feed on Steem Projects](https://steemprojects.com/projects/p/witness-price-feed/)_.\n\nIf you want to be notified about new updates from this project, register on Steem Projects and add Witness Price Feed to your favorite projects.\n","json_metadata":""}}
th_a steem_evaluator.cpp:682 do_apply

{"op":["comment",{"parent_author":"yabapmatt","parent_permlink":"another-price-feed-publishing-tool-for-witnesses","author":"steemprojects","permlink":"re-another-price-feed-publishing-tool-for-witnesses-20180310t001031","title":"","body":"\nThis post has been just added as new item to _[timeline of Witness Price Feed on Steem Projects](https://steemprojects.com/projects/p/witness-price-feed/)_.\n\nIf you want to be notified about new updates from this project, register on Steem Projects and add Witness Price Feed to your favorite projects.\n","json_metadata":""}]}
th_a database.cpp:2893 _apply_transaction

{"trx":{"ref_block_num":25449,"ref_block_prefix":445264557,"expiration":"2018-03-10T00:11:31","operations":[["comment",{"parent_author":"yabapmatt","parent_permlink":"another-price-feed-publishing-tool-for-witnesses","author":"steemprojects","permlink":"re-another-price-feed-publishing-tool-for-witnesses-20180310t001031","title":"","body":"\nThis post has been just added as new item to _[timeline of Witness Price Feed on Steem Projects](https://steemprojects.com/projects/p/witness-price-feed/)_.\n\nIf you want to be notified about new updates from this project, register on Steem Projects and add Witness Price Feed to your favorite projects.\n","json_metadata":""}]],"extensions":[],"signatures":["1f278723ef27b9193073b5350ce2d7fa30d49da5593033271022972413c00b45b7684dd298098561ee7acf0f008dfb7b6476236c36c854df849cbe70d80b9cdf83"]}}
th_a database.cpp:2897 _apply_transaction

{"trx":{"ref_block_num":25449,"ref_block_prefix":445264557,"expiration":"2018-03-10T00:11:31","operations":[["comment",{"parent_author":"yabapmatt","parent_permlink":"another-price-feed-publishing-tool-for-witnesses","author":"steemprojects","permlink":"re-another-price-feed-publishing-tool-for-witnesses-20180310t001031","title":"","body":"\nThis post has been just added as new item to _[timeline of Witness Price Feed on Steem Projects](https://steemprojects.com/projects/p/witness-price-feed/)_.\n\nIf you want to be notified about new updates from this project, register on Steem Projects and add Witness Price Feed to your favorite projects.\n","json_metadata":""}]],"extensions":[],"signatures":["1f278723ef27b9193073b5350ce2d7fa30d49da5593033271022972413c00b45b7684dd298098561ee7acf0f008dfb7b6476236c36c854df849cbe70d80b9cdf83"]}}
th_a database.cpp:660 push_transaction

{"call.method":"call","call.params":["network_broadcast_api","broadcast_transaction",[{"ref_block_num":25449,"ref_block_prefix":445264557,"expiration":"2018-03-10T00:11:31","operations":[["comment",{"parent_author":"yabapmatt","parent_permlink":"another-price-feed-publishing-tool-for-witnesses","author":"steemprojects","permlink":"re-another-price-feed-publishing-tool-for-witnesses-20180310t001031","title":"","body":"\nThis post has been just added as new item to _[timeline of Witness Price Feed on Steem Projects](https://steemprojects.com/projects/p/witness-price-feed/)_.\n\nIf you want to be notified about new updates from this project, register on Steem Projects and add Witness Price Feed to your favorite projects.\n","json_metadata":""}]],"extensions":[],"signatures":["1f278723ef27b9193073b5350ce2d7fa30d49da5593033271022972413c00b45b7684dd298098561ee7acf0f008dfb7b6476236c36c854df849cbe70d80b9cdf83"]}]]}
th_a websocket_api.cpp:124 on_message


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

File "/usr/local/lib/python3.6/site-packages/chroniker/models.py", line 1167, in handle_run
call_command(self.command, *args, **options)

File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 130, in call_command
return command.execute(*args, **defaults)

File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
output = self.handle(*args, **options)

File "/app/timeline/management/commands/timeline_event_inserter.py", line 19, in handle
for event in rulebook.fetch_new_events():

File "/app/timeline/services.py", line 96, in get_new_events
self.notify(post)

File "/app/timeline/services.py", line 111, in notify
raise Exception("Steem Notify Service Exception:\n\n{}\n\n{}".format(str(e), str(resposnse)))

Exception: Steem Notify Service Exception:

10 assert_exception: Assert Exception
(now - auth.last_post) > STEEMIT_MIN_REPLY_INTERVAL: You may only comment once every 20 seconds.
{"now":"2018-03-10T00:10:30","auth.last_post":"2018-03-10T00:10:12"}
th_a steem_evaluator.cpp:511 do_apply

{"o":{"parent_author":"yabapmatt","parent_permlink":"another-price-feed-publishing-tool-for-witnesses","author":"steemprojects","permlink":"re-another-price-feed-publishing-tool-for-witnesses-20180310t001031","title":"","body":"\nThis post has been just added as new item to _[timeline of Witness Price Feed on Steem Projects](https://steemprojects.com/projects/p/witness-price-feed/)_.\n\nIf you want to be notified about new updates from this project, register on Steem Projects and add Witness Price Feed to your favorite projects.\n","json_metadata":""}}
th_a steem_evaluator.cpp:682 do_apply

{"op":["comment",{"parent_author":"yabapmatt","parent_permlink":"another-price-feed-publishing-tool-for-witnesses","author":"steemprojects","permlink":"re-another-price-feed-publishing-tool-for-witnesses-20180310t001031","title":"","body":"\nThis post has been just added as new item to _[timeline of Witness Price Feed on Steem Projects](https://steemprojects.com/projects/p/witness-price-feed/)_.\n\nIf you want to be notified about new updates from this project, register on Steem Projects and add Witness Price Feed to your favorite projects.\n","json_metadata":""}]}
th_a database.cpp:2893 _apply_transaction

{"trx":{"ref_block_num":25449,"ref_block_prefix":445264557,"expiration":"2018-03-10T00:11:31","operations":[["comment",{"parent_author":"yabapmatt","parent_permlink":"another-price-feed-publishing-tool-for-witnesses","author":"steemprojects","permlink":"re-another-price-feed-publishing-tool-for-witnesses-20180310t001031","title":"","body":"\nThis post has been just added as new item to _[timeline of Witness Price Feed on Steem Projects](https://steemprojects.com/projects/p/witness-price-feed/)_.\n\nIf you want to be notified about new updates from this project, register on Steem Projects and add Witness Price Feed to your favorite projects.\n","json_metadata":""}]],"extensions":[],"signatures":["1f278723ef27b9193073b5350ce2d7fa30d49da5593033271022972413c00b45b7684dd298098561ee7acf0f008dfb7b6476236c36c854df849cbe70d80b9cdf83"]}}
th_a database.cpp:2897 _apply_transaction

{"trx":{"ref_block_num":25449,"ref_block_prefix":445264557,"expiration":"2018-03-10T00:11:31","operations":[["comment",{"parent_author":"yabapmatt","parent_permlink":"another-price-feed-publishing-tool-for-witnesses","author":"steemprojects","permlink":"re-another-price-feed-publishing-tool-for-witnesses-20180310t001031","title":"","body":"\nThis post has been just added as new item to _[timeline of Witness Price Feed on Steem Projects](https://steemprojects.com/projects/p/witness-price-feed/)_.\n\nIf you want to be notified about new updates from this project, register on Steem Projects and add Witness Price Feed to your favorite projects.\n","json_metadata":""}]],"extensions":[],"signatures":["1f278723ef27b9193073b5350ce2d7fa30d49da5593033271022972413c00b45b7684dd298098561ee7acf0f008dfb7b6476236c36c854df849cbe70d80b9cdf83"]}}
th_a database.cpp:660 push_transaction

{"call.method":"call","call.params":["network_broadcast_api","broadcast_transaction",[{"ref_block_num":25449,"ref_block_prefix":445264557,"expiration":"2018-03-10T00:11:31","operations":[["comment",{"parent_author":"yabapmatt","parent_permlink":"another-price-feed-publishing-tool-for-witnesses","author":"steemprojects","permlink":"re-another-price-feed-publishing-tool-for-witnesses-20180310t001031","title":"","body":"\nThis post has been just added as new item to _[timeline of Witness Price Feed on Steem Projects](https://steemprojects.com/projects/p/witness-price-feed/)_.\n\nIf you want to be notified about new updates from this project, register on Steem Projects and add Witness Price Feed to your favorite projects.\n","json_metadata":""}]],"extensions":[],"signatures":["1f278723ef27b9193073b5350ce2d7fa30d49da5593033271022972413c00b45b7684dd298098561ee7acf0f008dfb7b6476236c36c854df849cbe70d80b9cdf83"]}]]}
th_a websocket_api.cpp:124 on_message

None
```

**Comment by chuelay** [comment]
Good

**Comment by noisy** [comment]
fixed: https://github.com/noisy-witness/steemprojects.com/commit/f5ea935b0f52c6cf80f251a71f735adaf4303d09
